services:
  # certbot-renew:
  #   image: certbot/dns-cloudflare:latest
  #   container_name: certbot-renew
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #   environment:
  #     - CF_API_TOKEN=${CF_TOKEN}
  #   networks:
  #     - app-network
  #   command: >
  #     renew --dns-cloudflare

  acme-dnspod:
    image: neilpang/acme.sh:latest
    container_name: acme-dnspod
    volumes:
      - d:/.letsencrypt/dnspod/api.memeniu.xyz:/acme.sh
    environment:
      - TZ=Asia/Shanghai
      - DP_Id=${DP_Id}
      - DP_Key=${DP_Key}
    command: daemon
    restart: always

  acme-dnspod-qiniu:
    image: neilpang/acme.sh:latest
    container_name: acme-dnspod-qiniu
    volumes:
      - d:/.letsencrypt/dnspod/memeniu.xyz:/acme.sh
    environment:
      - TZ=Asia/Shanghai
      - DP_Id=${DP_Id}
      - DP_Key=${DP_Key}
    command: daemon
    restart: always

  acme-dnspod-qiniucdn:
    image: neilpang/acme.sh:latest
    container_name: acme-dnspod-qiniucdn
    volumes:
      - d:/.letsencrypt/dnspod/cdn.memeniu.xyz:/acme.sh
    environment:
      - TZ=Asia/Shanghai
      - DP_Id=${DP_Id}
      - DP_Key=${DP_Key}
    command: daemon
    restart: always

  acme-cloudflare:
    image: neilpang/acme.sh:latest
    container_name: acme-cloudflare
    volumes:
      - d:/.letsencrypt/cloudflare/meme.us.kg:/acme.sh
    environment:
      - TZ=Asia/Shanghai
      - CF_Token=${CF_TOKEN}
      - CF_Account_ID=${CF_ACCOUNT}
      - CF_Zone_ID=${CF_ZONE}
    command: daemon
    restart: always

  fastapi:
    image: registry.cn-chengdu.aliyuncs.com/memeking/pymecli:latest
    container_name: fastapi
    expose:
      - "8000"
    # volumes:
    #   - ./certbot/conf:/etc/letsencrypt
    environment:
      - CLASH_PROXY=socks5://192.168.123.7:7897
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      fast 0.0.0.0 --port 8000
      --rule https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release
      --my-rule https://raw.githubusercontent.com/meme2046/data/refs/heads/main/clash
      --proxy socks5://192.168.123.7:7897
    # depends_on:
    #   - certbot-renew
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    # image: nginx:alpine
    image: openresty/openresty:alpine
    container_name: nginx
    ports:
      - "8888:443"
      - "9999:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./files/.nginx:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./files/logs:/usr/local/openresty/nginx/logs # 挂载日志目录
      - ./files/favicon.ico:/usr/local/openresty/nginx/html/favicon.ico
      # - ./files/lua-scripts:/usr/local/openresty/nginx/lua-scripts \ # 挂载Lua脚本
      # - ./certbot/conf:/etc/letsencrypt # meme.us.kg
      # - ./dnspod-cert:/etc/letsencrypt/live/api.memeniu.xyz/ # api.memeniu.xyz
      # - d:/.mkcert/api.memeniu.xyz:/etc/letsencrypt/live/api.memeniu.xyz/ # api.memeniu.xyz, dnspod
      - "d:/.letsencrypt/cloudflare/meme.us.kg:/etc/letsencrypt/live/meme.us.kg"
      - "d:/.letsencrypt/dnspod/api.memeniu.xyz:/etc/letsencrypt/live/api.memeniu.xyz"
    depends_on:
      # - certbot-renew # 添加这个依赖
      - fastapi
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
