networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - d:/redis/data:/data
    command: >
      redis-server
      --bind 0.0.0.0
      --protected-mode no
      --appendonly no
      --requirepass ${REDIS_PASSWORD}
      --port 6379
    networks:
      - app-network
    restart: unless-stopped
