networks:
  app-network:
    driver: bridge

services:
  worker:
    environment:
      - TZ=Asia/Shanghai
    image: registry.cn-chengdu.aliyuncs.com/jusu/cron-worker:latest
    deploy:
      replicas: 3
    networks:
      - app-network
    restart: unless-stopped

  api:
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - d:/.mkcert:/etc/mkcert
    image: registry.cn-chengdu.aliyuncs.com/jusu/cron-api:latest
    container_name: api
    ports:
      - "8000:80"
    networks:
      - app-network
    restart: unless-stopped
