services:
  # ========== 服务端转发（外网IPv6入站 → 本地游戏回环）==========
  # 主世界 IPv6:10999 → 127.0.0.1:10999
  - name: server-master
    addr: "[240e:333:2cb6:4000:48c6:83ad:482b:63e7]:10999"
    listener:
      type: udp
    handler:
      type: udp
    forwarders:
      - addr: 127.0.0.1:10999

  # 洞穴 IPv6:10998 → 127.0.0.1:10998
  - name: server-cave
    addr: "[240e:333:2cb6:4000:48c6:83ad:482b:63e7]:10998"
    listener:
      type: udp
    handler:
      type: udp
    forwarders:
      - addr: 127.0.0.1:10998
