return {
	["client_mods_disabled"] = {
		["configuration_options"] = {},
		["enabled"] = true
	},
	["workshop-1185229307"] = {
		["configuration_options"] = 	{
			["CAMERA"] = true,
			["CAPTURE"] = false,
			["DAMAGE_NUMBERS"] = true,
			["DAMAGE_RESISTANCE"] = true,
			["FRAME_PHASES"] = true,
			["GLOBAL"] = true,
			["GLOBAL_NUMBERS"] = false,
			["HEADER_CLIENT"] = false,
			["HEADER_SERVER"] = false,
			["HORIZONTAL_OFFSET"] = 0,
			["TAG"] = "EPIC",
			["TRANSLATOR"] = false,
			["WETNESS_METER"] = false
		},
		["enabled"] = true
	},
	["workshop-3044756151"] = {
		["configuration_options"] = 	{
			["ANNOUNCE_MODE"] = true,
			["CLEANDAYS"] = 15,
			["axe"] = 3,
			["bee"] = 10,
			["beefalo"] = 50,
			["birdtrap"] = 10,
			["blueprint"] = 3,
			["bugnet"] = 3,
			["burntground"] = 5,
			["clean"] = true,
			["compass"] = 3,
			["cutgrass"] = 50,
			["deer"] = 10,
			["driftwood_log"] = 130,
			["earmuffshat"] = 3,
			["evergreen_sparse"] = 150,
			["feather"] = 2,
			["festival"] = 2,
			["firehound"] = 10,
			["fishingrod"] = 3,
			["flies"] = 10,
			["flint"] = 50,
			["frog"] = 20,
			["glommerfuel"] = 10,
			["guano"] = 1,
			["hammer"] = 3,
			["heatrock"] = 10,
			["hound"] = 10,
			["houndstooth"] = 2,
			["lang"] = true,
			["log"] = 50,
			["manrabbit_tail"] = 20,
			["marsh_tree"] = 100,
			["mosquitosack"] = 10,
			["nitre"] = 50,
			["oceanfishingrod"] = 3,
			["pickaxe"] = 3,
			["pinecone"] = 50,
			["pitchfork"] = 3,
			["pocket_scale"] = 3,
			["poop"] = 5,
			["razor"] = 3,
			["rock_petrified_tree"] = 150,
			["rocks"] = 50,
			["rocky"] = 20,
			["rottenegg"] = 2,
			["seeds"] = 3,
			["shovel"] = 3,
			["silk"] = 10,
			["skeleton_player"] = 20,
			["sketch"] = 1,
			["slurtle"] = 5,
			["slurtleslime"] = 2,
			["spear"] = 3,
			["spider"] = 10,
			["spiderden"] = 40,
			["spidergland"] = 10,
			["spoiled_fish"] = 2,
			["spoiled_food"] = 2,
			["stack"] = true,
			["stack_fireflies"] = true,
			["stack_scanning_range"] = 10,
			["stinger"] = 2,
			["tacklesketch"] = 1,
			["test_mode"] = false,
			["torch"] = 3,
			["trade"] = true,
			["trap"] = 30,
			["twiggytree"] = 150,
			["twigs"] = 50,
			["winterhat"] = 3
		},
		["enabled"] = true
	},
	["workshop-3486375086"] = {
		["configuration_options"] = 	{
			["DEBUGPrint"] = true,
			["client_mods_list"] = 		{
        ["workshop-2786299410"]={ config={ acidrain=true, meter=true, stage=true }, version="2.16" },
				["workshop-2873533916"] = 			{
					["config"] = 				{
						["Languages"] = "chinese",
						["action_queue_key"] = "KEY_LSHIFT",
						["always_clear_queue"] = true,
						["auto_collect"] = false,
						["auto_collect_key"] = "KEY_F4",
						["debug_mode"] = false,
						["deploy_on_grid"] = false,
						["double_click_range"] = 25,
						["double_click_speed"] = 0.3,
						["double_snake"] = false,
						["endless_deploy"] = false,
						["endless_deploy_key"] = "KEY_F5",
						["farm_grid"] = "3x3",
						["last_recipe_key"] = "KEY_C",
						["qaaq"] = false,
						["selection_color"] = "WHITE",
						["selection_opacity"] = 0.5,
						["tooth_trap_spacing"] = 2,
						["turf_grid_color"] = "WHITE",
						["turf_grid_key"] = "KEY_F3",
						["turf_grid_radius"] = 5
					},
					["version"] = "4.0"
				},
				["workshop-2997164720"] = 			{
					["config"] = 				{
						["Announce_Style"] = true,
						["Chat_Command"] = true,
						["Ping_Style"] = true,
						["lang"] = "auto",
						["remember"] = true
					},
					["version"] = "4.2.7-a"
				},
				["workshop-3115280970"] = 			{
					["config"] = 				{
						["Dark_filter"] = 1,
						["Sand storm"] = 0,
						["snow_intensity_allowed"] = 0
					},
					["version"] = "1.1"
				},
				["workshop-3293693889"] = 			{
					["config"] = 				{
						["MAPPING_LB_BACK"] = false,
						["MAPPING_LB_LT"] = false,
						["MAPPING_LB_RB_BACK"] = 6,
						["MAPPING_LB_RB_LT"] = 15,
						["MAPPING_LB_RB_RT"] = 14,
						["MAPPING_LB_RB_START"] = 7,
						["MAPPING_LB_RB_UP"] = false,
						["MAPPING_LB_RB_Y"] = false,
						["MAPPING_LB_START"] = false,
						["MAPPING_LB_UP"] = false,
						["MAPPING_LB_Y"] = false,
						["MAPPING_RB_BACK"] = false,
						["MAPPING_RB_LT"] = false,
						["MAPPING_RB_RT"] = false,
						["MAPPING_RB_START"] = false,
						["MAPPING_RB_UP"] = false,
						["MAPPING_RB_Y"] = false,
						["Title"] = "",
						["add_attackable_target_detect_radius"] = 0,
						["attack_all_direction"] = true,
						["change_craftingmenu"] = "scheme1",
						["change_wheel"] = "scheme1",
						["enable_force_control"] = true,
						["forbid_inspect_self"] = true,
						["force_attack_target"] = true,
						["force_ground_actions"] = true,
						["force_pause"] = true,
						["hide_inventory_hint"] = "none",
						["hide_world_item_hint"] = "none",
						["interact_all_direction"] = false,
						["interaction_target_detect_radius"] = 6,
						["language"] = true,
						["mount_and_dismount_must_press_RB"] = true,
						["reverse_rotation_hud_screen"] = false,
						["reverse_rotation_map_screen"] = false,
						["reverse_zoom_hud_screen"] = false,
						["reverse_zoom_map_screen"] = false,
						["show_backpack_widget"] = false,
						["show_map_widget"] = true,
						["woby_action_must_press_RB"] = true
					},
					["version"] = "0.1.43"
				},
				["workshop-3343140219"] = 			{
					["config"] = 				{
						["ACTION_TILL"] = true,
						["BADCOLOR"] = "red",
						["BADPLACERCOLOR"] = "red",
						["BADTILECOLOR"] = "red",
						["BIGGRIDSIZE"] = 2,
						["BUILDGRID"] = true,
						["CONTROLLEROFFSET"] = false,
						["CTRL"] = false,
						["GEOMETRY"] = "SQUARE",
						["GEOMETRYTOGGLEKEY"] = "V",
						["GOODCOLOR"] = "green",
						["GOODPLACERCOLOR"] = "green",
						["GOODTILECOLOR"] = "green",
						["HIDECURSOR"] = false,
						["HIDEPLACER"] = true,
						["KEYBOARDTOGGLEKEY"] = "B",
						["MEDGRIDSIZE"] = 6,
						["NEARTILECOLOR"] = "white",
						["REDUCECHESTSPACING"] = true,
						["SHOWMENU"] = true,
						["SMALLGRIDSIZE"] = 10,
						["SMARTSPACING"] = true,
						["SNAPGRIDKEY"] = "",
						["TIMEBUDGET"] = 0.1
					},
					["version"] = "3.2.01"
				},
				["workshop-3422869992"] = 			{
					["config"] = {},
					["version"] = "2026-04-28"
				},
				["workshop-3733804828"] = 			{
					["config"] = 				{
						["BADGE_BG_BRIGHTNESS"] = 60,
						["BADGE_BG_OPACITY"] = 100,
						["COLOR_DOMESTICATION_DEFAULT"] = "BEIGE",
						["COLOR_DOMESTICATION_ORNERY"] = "ORANGE",
						["COLOR_DOMESTICATION_PUDGY"] = "PURPLE",
						["COLOR_DOMESTICATION_RIDER"] = "BLUE",
						["COLOR_TIMER"] = "GREEN",
						["ClientConfig"] = false,
						["EnableSounds"] = false,
						["GapModifier"] = 0,
						["OffsetX"] = 0,
						["OffsetXFine"] = 0,
						["OffsetXMult"] = 1,
						["OffsetY"] = 0,
						["OffsetYFine"] = 0,
						["OffsetYMult"] = 1,
						["SEPARATOR_BADGE_COLORS"] = 1,
						["SEPARATOR_BADGE_SETTINGS"] = 1,
						["SEPARATOR_GENERAL"] = 1,
						["SEPARATOR_POSITIONING_X"] = 1,
						["SEPARATOR_POSITIONING_Y"] = 1,
						["Scale"] = 1,
						["ShowByDefault"] = true,
						["Theme"] = "Default",
						["ToggleKey"] = "KEY_T"
					},
					["version"] = "1.0.2"
				},
				["workshop-376333686"] = 			{
					["config"] = 				{
						["FLIPMOON"] = false,
						["HIDECAVECLOCK"] = false,
						["HUDSCALEFACTOR"] = 100,
						["SEASONOPTIONS"] = "Clock",
						["SHOWBEAVERNESS"] = true,
						["SHOWCLOCKTEXT"] = true,
						["SHOWMAXONNUMBERS"] = true,
						["SHOWMOON"] = 2,
						["SHOWNAUGHTINESS"] = true,
						["SHOWNEXTFULLMOON"] = true,
						["SHOWSTATNUMBERS"] = true,
						["SHOWTEMPBADGES"] = true,
						["SHOWTEMPERATURE"] = true,
						["SHOWWANINGMOON"] = true,
						["SHOWWORLDTEMP"] = false,
						["UNIT"] = "T"
					},
					["version"] = "1.9.3"
				}
			},
			["language"] = "auto"
		},
		["enabled"] = true
	},
	["workshop-3571706033"] = {
		["configuration_options"] = 	{
			["Draw over FoW"] = "disabled"
		},
		["enabled"] = true
	},
	["workshop-3590648641"] = {
		["configuration_options"] = 	{
			["maprevealer"] = true,
			["modify_player_scale"] = true
		},
		["enabled"] = true
	}
}
