services:
  dst:
    image: registry.cn-chengdu.aliyuncs.com/memeking/dmp:latest
    container_name: dmp-main
    restart: "no"
    # restart: always
    network_mode: bridge
    ports:
      - "8082:8082"
      - "11000-11002:11000-11002/udp"
      - "31001-31002:31001-31002/udp"
      - "41001-41002:41001-41002/udp"
      - "21001:21001/udp"
      # ⬇️不知道要不要开以下TCP端口
      - "11000-11002:11000-11002/tcp"
      - "31001-31002:31001-31002/tcp"
      - "41001-41002:41001-41002/tcp"
    environment:
      - TZ=Asia/Shanghai
      - DMP_PORT=8082
      - DMP_IN_CONTAINER=1
      # - PGID=$(id -g)
      # - PUID=$(id -u)
      # 日志等级设置为info (debug | info | warning | error)
      - LEVEL=warning
    volumes:
      # dmp 数据库目录
      - c:/dmp/data:/root/data
      # 饥荒存档目录
      - c:/dmp/klei:/root/.klei
      # dmp 文件所在目录
      - c:/dmp/dmp_files:/root/dmp_files
      # dmp 日志所在目录
      - c:/dmp/logs:/root/logs
      # Steam 文件目录
      - "c:/dmp/Steam:/root/Steam"
      # steamcmd 文件目录
      - c:/steamcmd:/root/steamcmd
      # 饥荒专用服务器目录
      - "c:/dst-dedicated-server:/root/dst"
