services:
  dst:
    image: registry.cn-chengdu.aliyuncs.com/memeking/dmp:latest
    container_name: dmp-main
    restart: "no"
    # restart: always
    network_mode: bridge
    ports:
      - "8082:8082"
      - "11001-11002:11001-11002/udp"
      - "31001-31002:31001-31002/udp"
      - "41001-41002:41001-41002/udp"
      # - "11001-11002:11001-11002/tcp"
      # - "31001-31002:31001-31002/tcp"
      # - "41001-41002:41001-41002/tcp"
    environment:
      - TZ=Asia/Shanghai
      - DMP_PORT=8082
      - DMP_IN_CONTAINER=1
      # 日志等级设置为info (debug | info | warning | error)
      - LEVEL=warning
    volumes:
      # dmp 数据库目录
      - c:/dst/dmp/data:/root/data
      # 饥荒专用服务器目录
      - "c:/dst/dmp/dst-server:/root/dst"
      # 饥荒存档目录
      - c:/dst/dmp/save:/root/.klei
      # dmp 文件所在目录
      - c:/dst/dmp/dmp_files:/root/dmp_files
      # dmp 日志所在目录
      - c:/dst/dmp/logs:/root/logs
      # steamcmd 文件目录
      - c:/dst/dmp/steamcmd:/root/steamcmd
      # Steam 文件目录
      - "c:/dst/dmp/Steam:/root/Steam"
