[window]
  # 窗口尺寸
  dimensions = { columns = 140, lines = 40 }
  padding = { x = 4, y = 0 }
  # 窗口位置
  position = "None"

[terminal]
  # 默认终端程序
  shell = { program = "nu" }

[general]
  # 实时配置热重载
  live_config_reload = true
  working_directory = "d:/.tmp"

[mouse]
  # 右键粘贴
  bindings = [{ mouse = "Right", action = "Paste" }]

[selection]
  # 选中复制
  save_to_clipboard = true

[font]
  # 字体族
  bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
  bold_italic = { family = "FiraCode Nerd Font Mono", style = "SemiBold" }
  italic = { family = "FiraCode Nerd Font Mono", style = "Regular" }
  normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
  # 字体大小
  size = 11.25
